---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: cd4pe
  name: cd4pe
  namespace: '{{repl or (ConfigOption "namespace") Namespace}}'
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cd4pe
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cd4pe
    spec:
      containers:
      - env:
        - name: DB_ENDPOINT
          value: postgres://postgres:5432/cd4pe
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: cd4pe-postgres
              key: password
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cd4pe-postgres
              key: user
        - name: PFI_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: cd4pe-pfi
              key: pfiSecretKey
        image: puppet/continuous-delivery-for-puppet-enterprise:3.5.0
        name: cd4pe
        ports:
        - name: cd4pe-web
          containerPort: 8080
        - name: cd4pe-backend
          containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "2"
        volumeMounts:
        - mountPath: /disk
          name: cache-volume
      hostname: cd4pe
      restartPolicy: Always
      volumes:
      - name: cache-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cd4pe
  name: cd4pe
  namespace: '{{repl or (ConfigOption "namespace") Namespace}}'
spec:
  ports:
  - name: cd4pe-web
    port: 8080
    targetPort: cd4pe-web
  - name: cd4pe-backend
    port: 8000
    targetPort: cd4pe-backend
  selector:
    app.kubernetes.io/name: cd4pe
---
apiVersion: v1
kind: Secret
metadata:
  name: cd4pe-pfi
  namespace: '{{repl or (ConfigOption "namespace") Namespace}}'
type: Opaque
stringData:
  # Gets the secret key from Replicated config.
  pfiSecretKey: '{{repl ConfigOption "pfi_secret_key"}}'
