apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: cd4pe-config
spec:
  groups:
  - name: application_setup
    title: Application Setup
    items:
    - name: namespace
      title: Kubernetes Namespace
      help_text: |
        The namespace to deploy in. The namespace needs to exist before deploying to it. Set blank to deploy to the same namespace as the admin console.
      type: text
      value: cd4pe
    - name: pfi_secret_key
      title: Database Encryption Secret Key
      help_text: |
        A 16-byte secret key used for AES encryption of secrets (such as PE access tokens) supplied to Continuous Delivery for PE.
        The default is not cryptographically-generated. Generate a new key by running: `dd bs=1 if=/dev/urandom count=16 2>/dev/null | base64`.
        Warning: changing this after initial rollout may make data in CD4PE inaccessible.
      type: password
      required: true
       # Uses Sprig functions to generate a (mostly) random 16-byte key
      value: '{{repl randAscii 16 | b64enc}}'
    # MinIO/PostgreSQL credentials are here to persist generated values but hidden to prevent changing them.
    # They should only be changed in the event of a security incident; doing so requires changing values
    # here (so CD4PE knows how to connect) and issuing commands to minio and postgres to change passwords.
    - name: postgres_user
      type: text
      hidden: true
      value: cd4pe
    - name: postgres_password
      type: password
      hidden: true
      value: '{{repl RandomString 24}}'
    - name: postgres_checksum
      type: text
      hidden: true
      value: repl{{sha256sum (cat (ConfigOption "postgres_user") ":" (ConfigOption "postgres_password"))}}
    - name: minio_access_key
      type: text
      hidden: true
      value: minio
    - name: minio_secret_key
      type: password
      hidden: true
      value: '{{repl RandomString 24}}'
    # Will be used once we can configure object store credentials as environment variables in CD4PE.
    - name: minio_checksum
      type: text
      hidden: true
      value: repl{{sha256sum (cat (ConfigOption "minio_access_key") ":" (ConfigOption "minio_secret_key"))}}
  - name: ingress_setup
    title: Ingress Setup
    description: |
      Setup how the application is exposed externally.
    items:
    - name: enable_ingress
      type: bool
      title: Enable Kubernetes Ingress
      help_text: |
        Uncheck this box to disable the Kubernetes Ingress resource.
      default: "1"
    - name: hostname
      type: text
      title: Hostname
      help_text: |
        Use this field to provide a hostname for your CD4PE Application installation.
      required: true
      when: repl{{ ConfigOptionEquals "enable_ingress" "1" }}
    - name: allow_http
      type: bool
      title: Allow Unsecured Access through HTTP
      help_text: |
        Uncheck this box to disable HTTP traffic between the client and the load balancer.
      default: "1"
      when: repl{{ ConfigOptionEquals "enable_ingress" "1" }}
    - name: annotations
      type: textarea
      title: Annotations
      help_text: |
        Use this textarea to provide annotations specific to your ingress controller.
        For example, `kubernetes.io/ingress.class: alb` when using the ALB ingress controller.
      when: repl{{ ConfigOptionEquals "enable_ingress" "1" }}
