apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: cd4pe-config
spec:
  groups:
  - name: application_setup
    title: Application Setup
    items:
    - name: pfi_secret_key
      title: PFI Secret Key
      help_text: |
        A 16-byte secret key used for AES encryption of secrets (such as PE access tokens) supplied to Continuous Delivery for PE.
        The default is not cryptographically-generated. Generate a new key by running: `dd bs=1 if=/dev/urandom count=16 2>/dev/null | base64`.
      type: password
      required: true
       # Uses Sprig functions to generate a (mostly) random 16-byte key
      value: '{{repl randAscii 16 | b64enc}}'
    - name: namespace
      title: Kubernetes Namespace
      help_text: |
        The namespace to deploy in. The namespace needs to exist before deploying to it. Set blank to deploy to the same namespace as the admin console.
      type: text
      value: cd4pe
    - name: ssl_port
      title: CD4PE SSL WebUI Port
      help_text: |
        Port to bind when SSL is enabled in CD4PE settings.
      type: text
      value: "8443"
    - name: backend_port
      title: CD4PE Backend Service Port
      help_text: |
        Port to bind for the backend service.
      type: text
      required: true
      value: "8000"
    - name: agent_port
      title: CD4PE Agent Service Port
      help_text: |
        Port to bind for the agent service.
      type: text
      required: true
      value: "7000"
  - name: ingress_setup
    title: Ingress Setup
    description: |
      Setup how the application is exposed externally.
    items:
    - name: enable_ingress
      type: bool
      title: Enable Kubernetes Ingress
      help_text: |
        Uncheck this box to disable the Kubernetes Ingress resource.
      default: "1"
    - name: hostname
      type: text
      title: Hostname
      help_text: |
        Use this field to provide a hostname for your Example Application installation.
      required: true
      when: repl{{ ConfigOptionEquals "enable_ingress" "1" }}
    - name: allow_http
      type: bool
      title: Allow Unsecured Access through HTTP
      help_text: |
        Uncheck this box to disable HTTP traffic between the client and the load balancer.
      default: "1"
      when: repl{{ ConfigOptionEquals "enable_ingress" "1" }}
    - name: annotations
      type: textarea
      title: Annotations
      help_text: |
        Use this textarea to provide annotations specific to your ingress controller.
        For example, `kubernetes.io/ingress.class: alb` when using the ALB ingress controller.
      when: repl{{ ConfigOptionEquals "enable_ingress" "1" }}
