---
apiVersion: v1
kind: Secret
metadata:
  name: cd4pe-postgres
  namespace: '{{repl or (ConfigOption "namespace") Namespace }}'
type: Opaque
stringData:
  user: cd4pe
  password: '{{repl ConfigOption "postgres_password"}}'
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: cd4pe-postgres
  name: postgres
  namespace: '{{repl or (ConfigOption "namespace") Namespace}}'
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cd4pe-postgres
  serviceName: postgres
  template:
    metadata:
      annotations:
        # Trigger restarting the pod when password changes
        checksum/password: repl{{sha256sum (ConfigOption "postgres_password")}}
      labels:
        app.kubernetes.io/name: cd4pe-postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cd4pe-postgres
              key: password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: cd4pe-postgres
              key: user
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        image: postgres:9.6
        name: postgres
        ports:
        - name: postgres
          containerPort: 5432
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "4"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: cd4pe-postgres
      hostname: postgres
      restartPolicy: Always
      volumes:
      - name: cd4pe-postgres
        persistentVolumeClaim:
          claimName: cd4pe-postgres
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cd4pe-postgres
  name: postgres
  namespace: '{{repl or (ConfigOption "namespace") Namespace}}'
spec:
  ports:
  - port: 5432
    targetPort: postgres
  clusterIP: None
  selector:
    app.kubernetes.io/name: cd4pe-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: cd4pe-postgres
  name: cd4pe-postgres
  namespace: '{{repl or (ConfigOption "namespace") Namespace}}'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
