---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: cd4pe-postgres
  name: postgres
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cd4pe-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cd4pe-postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: cd4pe
        - name: POSTGRES_USER
          value: cd4pe
        image: postgres:9.6
        name: postgres
        ports:
        - name: postgres
          containerPort: 5432
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "4"
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: cd4pe-postgres
      hostname: postgres
      restartPolicy: Always
      volumes:
      - name: cd4pe-postgres
        persistentVolumeClaim:
          claimName: cd4pe-postgres
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cd4pe-postgres
  name: postgres
spec:
  ports:
  - port: 5432
    targetPort: postgres
  selector:
    app.kubernetes.io/name: cd4pe-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: cd4pe-postgres
  name: cd4pe-postgres
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
