apiVersion: troubleshoot.replicated.com/v1beta1
kind: Collector
metadata:
  name: collector-sample
spec:
  collectors:
  - clusterInfo: {}
  - clusterResources: {}
  - logs:
      name: puppet
      selector:
        - app.kubernetes.io/name=cd4pe
      namespace: cd4pe
      limits:
        maxAge: 30d
        maxLines: 10000
